"""Create a B5 4K print image with oversampled Krea2 tile regeneration.

The source is first enlarged to a working canvas without generation.  Each
complete 256 px working tile is then resized to 1024 px, regenerated by Krea2,
and reduced as a complete tile to 512 px.  Overlapping 512 px results are
low-frequency anchored to a deterministic 2x base and feather-composited.
With the default 2x working canvas, a 1K source is drawn at roughly 4K and the
complete generated canvas is finally reduced to the B5 target dimensions.
"""

from __future__ import annotations

import argparse
import base64
from dataclasses import asdict
from datetime import datetime
import hashlib
import io
import json
import math
from pathlib import Path
import secrets
import shutil
import sys
import time

import cv2
import numpy as np
from PIL import Image, ImageOps, PngImagePlugin
import requests

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from modules.krea2_quality import adaptive_detail_guard
from modules_forge.krea2_highres import krea2_detail_prompt
from modules_forge.krea2_upscale import replace_infotext_size
from modules_forge.vram_canvas import coordinate_seed, frequency_detail_delta
from tools.apply_krea2_identity_guard import (
    ProtectionEllipse,
    protection_mask,
    parse_protection_ellipse,
)
from tools.vram_canvas_highres import prompt_from_png


DEFAULT_API = "http://127.0.0.1:7861"
DEFAULT_TARGET_SIZE = (2896, 4096)
B5_HEIGHT_MM = 257.0
LOCAL_TILE_PROMPT = (
    "An s5p2style faithful high-resolution restoration of the exact supplied "
    "local image crop. Treat the supplied crop as binding ground truth. Preserve "
    "every existing contour, object, color, value, material, light, and crop edge "
    "at the same location. This input is only a local crop, not a complete scene; "
    "never infer or reconstruct the wider scene. Add only fine edge clarity and "
    "material microtexture already directly supported by visible structure in this "
    "crop. Do not add, remove, duplicate, reinterpret, or relocate anything. Never "
    "turn texture, shadows, books, fabric, wood grain, highlights, or empty space "
    "into miniature people, characters, faces, eyes, creatures, slime, ornaments, "
    "text, symbols, scenery, or repeated motifs. No new content, hallucinated "
    "objects, repeated patterns, border, seam, logo, signature, or watermark."
)


def emit(message: str) -> None:
    sys.stdout.write(f"{message}\n")
    sys.stdout.flush()


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(4 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def resolve_seed(seed: int) -> int:
    if seed < -1 or seed >= 2**32:
        raise ValueError("--seed must be -1 or a non-negative 32-bit integer")
    return secrets.randbelow(2**32) if seed == -1 else seed


def tile_origins(length: int, tile_size: int, overlap: int) -> list[int]:
    """Return balanced origins that cover an axis with complete overlapping tiles."""

    length = int(length)
    tile_size = int(tile_size)
    overlap = int(overlap)
    if length < tile_size:
        raise ValueError("canvas axis must be at least one complete tile")
    if overlap < 0 or overlap >= tile_size:
        raise ValueError("tile overlap must satisfy 0 <= overlap < tile size")
    if length == tile_size:
        return [0]
    stride = tile_size - overlap
    count = int(math.ceil((length - tile_size) / stride)) + 1
    return [
        int(round(index * (length - tile_size) / (count - 1))) for index in range(count)
    ]


def axis_blend_weight(
    length: int,
    feather: int,
    *,
    touches_start: bool,
    touches_end: bool,
) -> np.ndarray:
    if length <= 0:
        raise ValueError("weight length must be > 0")
    if feather < 0:
        raise ValueError("weight feather must be >= 0")
    feather = min(int(feather), length // 2)
    weight = np.ones(length, dtype=np.float32)
    if feather == 0:
        return weight
    position = (np.arange(feather, dtype=np.float32) + 0.5) / feather
    ramp = position * position * (3.0 - 2.0 * position)
    if not touches_start:
        weight[:feather] = ramp
    if not touches_end:
        weight[-feather:] = ramp[::-1]
    return weight


def tile_blend_weight(
    tile_size: int,
    feather: int,
    *,
    x0: int,
    y0: int,
    canvas_size: tuple[int, int],
) -> np.ndarray:
    canvas_width, canvas_height = canvas_size
    x_weight = axis_blend_weight(
        tile_size,
        feather,
        touches_start=x0 == 0,
        touches_end=x0 + tile_size == canvas_width,
    )
    y_weight = axis_blend_weight(
        tile_size,
        feather,
        touches_start=y0 == 0,
        touches_end=y0 + tile_size == canvas_height,
    )
    return y_weight[:, None] * x_weight[None, :]


def image_to_b64_png(image: Image.Image) -> str:
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    return base64.b64encode(buffer.getvalue()).decode("ascii")


def decode_b64_image(value: str) -> Image.Image:
    payload = value.split(",", 1)[-1]
    with Image.open(io.BytesIO(base64.b64decode(payload))) as opened:
        return opened.convert("RGB")


def source_gated_detail(
    candidate: Image.Image,
    base: Image.Image,
    *,
    radius: int,
    gain: float,
    max_delta: float,
    structure_sigma: float,
    base_detail_sigma: float,
) -> tuple[Image.Image, dict[str, float]]:
    """Keep only source-supported regenerated high-frequency detail."""

    if candidate.size != base.size:
        raise ValueError("candidate and base tile sizes must match")
    base_values = np.asarray(base.convert("RGB"), dtype=np.float32)
    delta, gate_report = frequency_detail_delta(
        np.asarray(candidate.convert("RGB"), dtype=np.uint8),
        np.asarray(base.convert("RGB"), dtype=np.uint8),
        radius=radius,
        gain=gain,
        max_delta=max_delta,
        structure_sigma=structure_sigma,
        base_detail_sigma=base_detail_sigma,
    )
    result_values = np.clip(np.rint(base_values + delta), 0, 255).astype(np.uint8)
    report = {
        "mean_abs_rgb_delta": float(np.mean(np.abs(delta), dtype=np.float64)),
        "p95_abs_rgb_delta": float(np.percentile(np.abs(delta), 95.0)),
        "max_abs_rgb_delta": float(np.max(np.abs(delta))),
        "clipped_delta_fraction": gate_report["clipped_fraction"],
        **gate_report,
    }
    return Image.fromarray(result_values), report


def low_frequency_detail(
    candidate: Image.Image,
    base: Image.Image,
    *,
    sigma: float,
    max_delta: float,
) -> tuple[Image.Image, dict[str, float]]:
    """Keep bounded regenerated detail while replacing the candidate low band."""

    if candidate.size != base.size:
        raise ValueError("candidate and base tile sizes must match")
    if not math.isfinite(float(sigma)) or sigma <= 0:
        raise ValueError("low-frequency sigma must be > 0")
    if not math.isfinite(float(max_delta)) or max_delta <= 0:
        raise ValueError("maximum tile delta must be > 0")
    candidate_values = np.asarray(candidate.convert("RGB"), dtype=np.float32)
    base_values = np.asarray(base.convert("RGB"), dtype=np.float32)
    candidate_low = cv2.GaussianBlur(
        candidate_values,
        (0, 0),
        sigmaX=float(sigma),
        sigmaY=float(sigma),
        borderType=cv2.BORDER_REFLECT_101,
    )
    base_low = cv2.GaussianBlur(
        base_values,
        (0, 0),
        sigmaX=float(sigma),
        sigmaY=float(sigma),
        borderType=cv2.BORDER_REFLECT_101,
    )
    anchored = candidate_values + (base_low - candidate_low)
    raw_delta = anchored - base_values
    delta = np.clip(raw_delta, -float(max_delta), float(max_delta))
    result_values = np.clip(np.rint(base_values + delta), 0, 255).astype(np.uint8)
    return Image.fromarray(result_values), {
        "mean_abs_rgb_delta": float(np.mean(np.abs(delta), dtype=np.float64)),
        "p95_abs_rgb_delta": float(np.percentile(np.abs(delta), 95.0)),
        "max_abs_rgb_delta": float(np.max(np.abs(delta))),
        "clipped_delta_fraction": float(np.mean(np.abs(raw_delta) >= float(max_delta))),
    }


def scale_protection_regions(
    regions: list[ProtectionEllipse],
    scale: float,
) -> list[ProtectionEllipse]:
    if not math.isfinite(float(scale)) or scale <= 0:
        raise ValueError("protection scale must be > 0")
    return [
        ProtectionEllipse(
            label=region.label,
            box=tuple(int(round(value * scale)) for value in region.box),
            feather=max(1, int(round(region.feather * scale))),
        )
        for region in regions
    ]


def apply_stage_protection(
    candidate: Image.Image,
    deterministic_base: Image.Image,
    regions: list[ProtectionEllipse],
) -> tuple[Image.Image, dict | None]:
    if not regions:
        return candidate, None
    mask, report = protection_mask(candidate.size, regions)
    return Image.composite(deterministic_base, candidate, mask), report


def request_json(
    method: str, url: str, *, timeout: float, payload: dict | None = None
) -> dict:
    response = requests.request(method, url, timeout=timeout, json=payload)
    if response.status_code >= 400:
        detail = response.text[:1500].replace("\n", " ")
        raise RuntimeError(f"Forge API {response.status_code} for {url}: {detail}")
    value = response.json()
    if not isinstance(value, dict):
        raise RuntimeError(f"Forge returned a non-object response for {url}")
    return value


def validate_forge(api: str, timeout: float) -> dict:
    options = request_json(
        "GET", f"{api.rstrip('/')}/sdapi/v1/options", timeout=timeout
    )
    checkpoint = Path(str(options.get("sd_model_checkpoint") or "")).name
    normalized_checkpoint = "".join(
        character for character in checkpoint.casefold() if character.isalnum()
    )
    if "krea2" not in normalized_checkpoint:
        raise RuntimeError(
            "Forge must have a Krea2 checkpoint selected before tile regeneration"
        )
    additional = options.get("forge_additional_modules") or []
    if isinstance(additional, str):
        additional = [additional]
    normalized_modules = [
        "".join(
            character
            for character in Path(str(value)).name.casefold()
            if character.isalnum()
        )
        for value in additional
    ]
    if not any("qwenimagevae" in value for value in normalized_modules):
        raise RuntimeError("Krea2 tile regeneration requires qwen_image_vae")
    if not any("qwen3vl" in value for value in normalized_modules):
        raise RuntimeError("Krea2 tile regeneration requires a qwen3vl text encoder")
    return {
        "checkpoint": checkpoint,
        "additional_modules": [Path(str(value)).name for value in additional],
    }


def regenerate_tile(
    tile: Image.Image,
    *,
    api: str,
    prompt: str,
    negative_prompt: str,
    seed: int,
    steps: int,
    denoise: float,
    sampler: str,
    scheduler: str,
    cfg: float,
    shift: float,
    process_edge: int,
    output_edge: int,
    timeout: float,
) -> tuple[Image.Image, float]:
    process_input = tile.resize((process_edge, process_edge), Image.Resampling.LANCZOS)
    payload = {
        "init_images": [image_to_b64_png(process_input)],
        "prompt": prompt,
        "negative_prompt": negative_prompt,
        "seed": seed,
        "sampler_name": sampler,
        "scheduler": scheduler,
        "steps": steps,
        "cfg_scale": cfg,
        "distilled_cfg_scale": shift,
        "width": process_edge,
        "height": process_edge,
        "resize_mode": 0,
        "denoising_strength": denoise,
        "n_iter": 1,
        "batch_size": 1,
        "restore_faces": False,
        "tiling": False,
        "send_images": True,
        "save_images": False,
        "include_init_images": False,
    }
    started = time.perf_counter()
    response = request_json(
        "POST",
        f"{api.rstrip('/')}/sdapi/v1/img2img",
        timeout=timeout,
        payload=payload,
    )
    elapsed = time.perf_counter() - started
    images = response.get("images") or []
    if not images:
        raise RuntimeError("Forge returned no regenerated tile")
    regenerated = decode_b64_image(images[0])
    if regenerated.size != (process_edge, process_edge):
        raise RuntimeError(
            f"Forge returned tile {regenerated.size}; expected {process_edge}x{process_edge}"
        )
    return (
        regenerated.resize((output_edge, output_edge), Image.Resampling.LANCZOS),
        elapsed,
    )


def close_memmap(values: np.memmap | None) -> None:
    if values is None:
        return
    values.flush()
    mmap = getattr(values, "_mmap", None)
    if mmap is not None:
        mmap.close()


def remove_scoped_tree(path: Path, *, expected_parent: Path) -> None:
    """Remove one known child directory after resolving its exact scope."""

    resolved_path = path.resolve(strict=False)
    resolved_parent = expected_parent.resolve(strict=False)
    if resolved_path.parent != resolved_parent:
        raise RuntimeError(
            f"refusing to remove directory outside expected parent: {resolved_path}"
        )
    if resolved_path == resolved_parent:
        raise RuntimeError(f"refusing to remove parent directory: {resolved_path}")
    if resolved_path.exists():
        shutil.rmtree(resolved_path)


def regenerate_stage(
    source: Image.Image,
    args: argparse.Namespace,
    *,
    prompt: str,
    negative_prompt: str,
    global_seed: int,
    original_size: tuple[int, int],
    original_regions: list[ProtectionEllipse],
    stage_index: int,
    work_dir: Path,
    output_dir: Path,
) -> tuple[Image.Image, dict]:
    stage_number = stage_index + 1
    source_width, source_height = source.size
    target_size = (source_width * 2, source_height * 2)
    deterministic_base = source.resize(target_size, Image.Resampling.LANCZOS)
    input_origins_x = tile_origins(source_width, args.tile_size, args.overlap)
    input_origins_y = tile_origins(source_height, args.tile_size, args.overlap)
    total_tiles = len(input_origins_x) * len(input_origins_y)
    output_tile_size = args.tile_size * 2
    output_feather = args.overlap * 2
    accumulator_path = work_dir / f"stage_{stage_number:02d}_rgb.float32"
    weight_path = work_dir / f"stage_{stage_number:02d}_weight.float32"
    accumulator = np.memmap(
        accumulator_path,
        dtype=np.float32,
        mode="w+",
        shape=(target_size[1], target_size[0], 3),
    )
    weight_sum = np.memmap(
        weight_path,
        dtype=np.float32,
        mode="w+",
        shape=(target_size[1], target_size[0]),
    )
    accumulator[:] = 0.0
    weight_sum[:] = 0.0
    records = []
    stage_started = time.perf_counter()
    try:
        sequence = 0
        for input_y0 in input_origins_y:
            for input_x0 in input_origins_x:
                sequence += 1
                tile = source.crop(
                    (
                        input_x0,
                        input_y0,
                        input_x0 + args.tile_size,
                        input_y0 + args.tile_size,
                    )
                )
                output_x0 = input_x0 * 2
                output_y0 = input_y0 * 2
                base_tile = deterministic_base.crop(
                    (
                        output_x0,
                        output_y0,
                        output_x0 + output_tile_size,
                        output_y0 + output_tile_size,
                    )
                )
                tile_seed = coordinate_seed(
                    global_seed,
                    stage_number,
                    input_x0,
                    input_y0,
                )
                emit(
                    f"STAGE={stage_number}/{args.stages} TILE={sequence}/{total_tiles} "
                    f"INPUT={input_x0},{input_y0},{args.tile_size}x{args.tile_size} "
                    f"PROCESS={args.process_edge} OUTPUT={output_tile_size} "
                    f"DENOISE={args.denoise:.3f} SEED={tile_seed}"
                )
                regenerated, elapsed = regenerate_tile(
                    tile,
                    api=args.api,
                    prompt=prompt,
                    negative_prompt=negative_prompt,
                    seed=tile_seed,
                    steps=args.steps,
                    denoise=args.denoise,
                    sampler=args.sampler,
                    scheduler=args.scheduler,
                    cfg=args.cfg,
                    shift=args.shift,
                    process_edge=args.process_edge,
                    output_edge=output_tile_size,
                    timeout=args.timeout,
                )
                if args.merge_mode == "low_anchor":
                    anchored, anchor_report = low_frequency_detail(
                        regenerated,
                        base_tile,
                        sigma=args.low_anchor_sigma,
                        max_delta=args.max_tile_delta,
                    )
                else:
                    anchored, anchor_report = source_gated_detail(
                        regenerated,
                        base_tile,
                        radius=args.detail_radius,
                        gain=args.detail_gain,
                        max_delta=args.max_tile_delta,
                        structure_sigma=args.structure_sigma,
                        base_detail_sigma=args.base_detail_sigma,
                    )
                weight = tile_blend_weight(
                    output_tile_size,
                    output_feather,
                    x0=output_x0,
                    y0=output_y0,
                    canvas_size=target_size,
                )
                output_slice = np.s_[
                    output_y0 : output_y0 + output_tile_size,
                    output_x0 : output_x0 + output_tile_size,
                ]
                accumulator[output_slice] += (
                    np.asarray(anchored, dtype=np.float32) * weight[..., None]
                )
                weight_sum[output_slice] += weight
                records.append(
                    {
                        "sequence": sequence,
                        "input_box": [
                            input_x0,
                            input_y0,
                            input_x0 + args.tile_size,
                            input_y0 + args.tile_size,
                        ],
                        "output_box": [
                            output_x0,
                            output_y0,
                            output_x0 + output_tile_size,
                            output_y0 + output_tile_size,
                        ],
                        "seed": tile_seed,
                        "elapsed_seconds": elapsed,
                        "anchor": anchor_report,
                    }
                )
                emit(
                    f"STAGE={stage_number}/{args.stages} TILE={sequence}/{total_tiles} "
                    f"DONE={elapsed:.2f}s DELTA_MEAN={anchor_report['mean_abs_rgb_delta']:.3f}"
                )
        accumulator.flush()
        weight_sum.flush()
        if float(np.min(weight_sum)) <= 0.0:
            raise RuntimeError("tile blend left uncovered output pixels")

        result_path = work_dir / f"stage_{stage_number:02d}_result.uint8"
        result_values = np.memmap(
            result_path,
            dtype=np.uint8,
            mode="w+",
            shape=(target_size[1], target_size[0], 3),
        )
        try:
            for y0 in range(0, target_size[1], 256):
                y1 = min(target_size[1], y0 + 256)
                normalized = (
                    np.asarray(accumulator[y0:y1], dtype=np.float32)
                    / np.asarray(weight_sum[y0:y1], dtype=np.float32)[..., None]
                )
                result_values[y0:y1] = np.clip(np.rint(normalized), 0, 255).astype(
                    np.uint8
                )
            result_values.flush()
            result = Image.fromarray(np.asarray(result_values).copy())
        finally:
            close_memmap(result_values)

        scale = target_size[0] / original_size[0]
        stage_regions = scale_protection_regions(original_regions, scale)
        result, protection_report = apply_stage_protection(
            result,
            deterministic_base,
            stage_regions,
        )
        stage_path = (
            output_dir
            / f"stage_{stage_number:02d}_{target_size[0]}x{target_size[1]}.png"
        )
        result.save(stage_path, format="PNG", optimize=True)
        return result, {
            "stage": stage_number,
            "source_size": [source_width, source_height],
            "target_size": list(target_size),
            "tile_size": args.tile_size,
            "process_edge": args.process_edge,
            "output_tile_size": output_tile_size,
            "overlap": args.overlap,
            "output_overlap": output_feather,
            "tile_count": total_tiles,
            "elapsed_seconds": time.perf_counter() - stage_started,
            "protection": protection_report,
            "output": str(stage_path),
            "tiles": records,
        }
    finally:
        close_memmap(accumulator)
        close_memmap(weight_sum)


def pnginfo_for_output(source_info: dict, summary: dict) -> PngImagePlugin.PngInfo:
    pnginfo = PngImagePlugin.PngInfo()
    for key, value in source_info.items():
        if isinstance(value, str) and key not in {
            "parameters",
            "krea2_b5_tile_regenerate",
        }:
            pnginfo.add_text(key, value)
    parameters = str(source_info.get("parameters") or "")
    if parameters:
        source_size = tuple(summary["source_size"])
        target_size = tuple(summary["target_size"])
        parameters = replace_infotext_size(
            parameters,
            source_size[0],
            source_size[1],
            target_size[0],
            target_size[1],
        )
        parameters += (
            f", Krea2 B5 Tile Regenerate: {summary['tile_size']}->"
            f"{summary['process_edge']}->{summary['tile_size'] * 2}, "
            f"Stages: {summary['stages']}"
        )
        pnginfo.add_text("parameters", parameters)
    pnginfo.add_text(
        "krea2_b5_tile_regenerate",
        json.dumps(summary, ensure_ascii=False, separators=(",", ":")),
    )
    return pnginfo


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--api", default=DEFAULT_API)
    parser.add_argument("--output-root", required=True, type=Path)
    parser.add_argument("--prompt", default=None)
    parser.add_argument("--negative-prompt", default=None)
    parser.add_argument(
        "--append-guidance", action=argparse.BooleanOptionalAction, default=False
    )
    parser.add_argument("--target-width", type=int, default=DEFAULT_TARGET_SIZE[0])
    parser.add_argument("--target-height", type=int, default=DEFAULT_TARGET_SIZE[1])
    parser.add_argument("--tile-size", type=int, default=256)
    parser.add_argument("--process-edge", type=int, default=1024)
    parser.add_argument("--overlap", type=int, default=64)
    parser.add_argument("--working-scale", type=int, choices=(1, 2), default=2)
    parser.add_argument("--stages", type=int, choices=(1, 2), default=1)
    parser.add_argument("--steps", type=int, default=6)
    parser.add_argument("--denoise", type=float, default=0.12)
    parser.add_argument("--sampler", default="DPM++ 2M SDE")
    parser.add_argument("--scheduler", default="Simple")
    parser.add_argument("--cfg", type=float, default=1.0)
    parser.add_argument("--shift", type=float, default=1.15)
    parser.add_argument("--seed", type=int, default=-1)
    parser.add_argument(
        "--merge-mode",
        choices=("low_anchor", "source_gate"),
        default="low_anchor",
    )
    parser.add_argument("--low-anchor-sigma", type=float, default=16.0)
    parser.add_argument("--detail-radius", type=int, default=8)
    parser.add_argument("--detail-gain", type=float, default=1.15)
    parser.add_argument("--max-tile-delta", type=float, default=16.0)
    parser.add_argument("--structure-sigma", type=float, default=12.0)
    parser.add_argument("--base-detail-sigma", type=float, default=2.5)
    parser.add_argument("--print-detail-strength", type=float, default=0.35)
    parser.add_argument("--print-detail-radius", type=float, default=1.0)
    parser.add_argument("--print-detail-threshold", type=float, default=0.7)
    parser.add_argument("--print-max-detail-delta", type=float, default=3.0)
    parser.add_argument(
        "--protect-ellipse", action="append", type=parse_protection_ellipse, default=[]
    )
    parser.add_argument("--timeout", type=float, default=900.0)
    return parser


def validate_args(args: argparse.Namespace) -> None:
    if args.target_width <= 0 or args.target_height <= 0:
        raise ValueError("B5 target dimensions must be > 0")
    if args.tile_size <= 0 or args.process_edge <= args.tile_size:
        raise ValueError("process edge must be larger than tile size")
    if args.process_edge % 16 != 0:
        raise ValueError("process edge must be divisible by 16")
    if args.process_edge <= args.tile_size * 2:
        raise ValueError("process edge must be larger than the reduced output tile")
    if args.overlap < 0 or args.overlap >= args.tile_size:
        raise ValueError("overlap must satisfy 0 <= overlap < tile size")
    if args.steps <= 0:
        raise ValueError("steps must be > 0")
    if not 0 <= args.denoise <= 1:
        raise ValueError("denoise must be between 0 and 1")
    if args.timeout <= 0:
        raise ValueError("timeout must be > 0")
    for value, name in (
        (args.detail_radius, "detail radius"),
        (args.detail_gain, "detail gain"),
        (args.max_tile_delta, "maximum tile delta"),
        (args.structure_sigma, "structure sigma"),
        (args.base_detail_sigma, "base detail sigma"),
        (args.low_anchor_sigma, "low-frequency anchor sigma"),
        (args.print_detail_radius, "print detail radius"),
        (args.print_detail_threshold, "print detail threshold"),
        (args.print_max_detail_delta, "print maximum detail delta"),
    ):
        if not math.isfinite(float(value)) or float(value) <= 0:
            raise ValueError(f"{name} must be finite and > 0")
    if not 0 <= args.print_detail_strength <= 1:
        raise ValueError("print detail strength must be between 0 and 1")


def main() -> int:
    args = build_parser().parse_args()
    validate_args(args)
    if not args.input.is_file():
        raise FileNotFoundError(args.input)
    args.seed = resolve_seed(args.seed)
    with Image.open(args.input) as opened:
        opened.load()
        source_info = dict(opened.info)
        source = ImageOps.exif_transpose(opened).convert("RGB")
    if source.width < args.tile_size or source.height < args.tile_size:
        raise ValueError("input image is smaller than one complete source tile")
    generated_size = (
        source.width * args.working_scale * (2**args.stages),
        source.height * args.working_scale * (2**args.stages),
    )
    if max(generated_size) > 8192:
        raise ValueError(
            f"generated working canvas {generated_size[0]}x{generated_size[1]} "
            "exceeds the guarded 8192 px long-edge limit"
        )
    if generated_size[0] < args.target_width or generated_size[1] < args.target_height:
        raise ValueError(
            f"generated working canvas {generated_size[0]}x{generated_size[1]} is "
            f"smaller than target {args.target_width}x{args.target_height}; "
            "the final operation would enlarge instead of reduce"
        )
    png_prompt, _ = prompt_from_png(args.input)
    prompt = args.prompt if args.prompt is not None else LOCAL_TILE_PROMPT
    negative_prompt = args.negative_prompt if args.negative_prompt is not None else ""
    if args.append_guidance:
        prompt = krea2_detail_prompt(prompt)

    forge = validate_forge(args.api, min(args.timeout, 30.0))
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    incomplete_dir = args.output_root / f"_incomplete_b5_tiles_{stamp}"
    final_dir = args.output_root / f"b5_tiles_{stamp}"
    if incomplete_dir.exists() or final_dir.exists():
        raise FileExistsError("timestamped output directory already exists")
    incomplete_dir.mkdir(parents=True)
    work_dir = incomplete_dir / "work"
    work_dir.mkdir()
    started = time.perf_counter()
    manifest = {
        "format_version": 1,
        "algorithm": "Krea2 complete-tile oversampled B5 regeneration",
        "input": {
            "path": str(args.input),
            "sha256": file_sha256(args.input),
            "size": list(source.size),
        },
        "source_size": list(source.size),
        "working_input_size": [
            source.width * args.working_scale,
            source.height * args.working_scale,
        ],
        "generated_canvas_size": list(generated_size),
        "target_size": [args.target_width, args.target_height],
        "tile_size": args.tile_size,
        "process_edge": args.process_edge,
        "reduced_tile_size": args.tile_size * 2,
        "overlap": args.overlap,
        "working_scale": args.working_scale,
        "stages": args.stages,
        "steps": args.steps,
        "denoise": args.denoise,
        "detail_filter": {
            "mode": args.merge_mode,
            "low_anchor_sigma": args.low_anchor_sigma,
            "radius": args.detail_radius,
            "gain": args.detail_gain,
            "maximum_delta": args.max_tile_delta,
            "structure_sigma": args.structure_sigma,
            "base_detail_sigma": args.base_detail_sigma,
        },
        "seed": args.seed,
        "source_prompt_sha256": hashlib.sha256(png_prompt.encode("utf-8")).hexdigest(),
        "prompt_sha256": hashlib.sha256(prompt.encode("utf-8")).hexdigest(),
        "negative_prompt_sha256": hashlib.sha256(
            negative_prompt.encode("utf-8")
        ).hexdigest(),
        "forge": forge,
        "protection_regions": [asdict(value) for value in args.protect_ellipse],
        "stage_reports": [],
    }
    try:
        current = source.resize(
            (
                source.width * args.working_scale,
                source.height * args.working_scale,
            ),
            Image.Resampling.LANCZOS,
        )
        for stage_index in range(args.stages):
            current, stage_report = regenerate_stage(
                current,
                args,
                prompt=prompt,
                negative_prompt=negative_prompt,
                global_seed=args.seed,
                original_size=source.size,
                original_regions=list(args.protect_ellipse),
                stage_index=stage_index,
                work_dir=work_dir,
                output_dir=incomplete_dir,
            )
            manifest["stage_reports"].append(stage_report)
            (incomplete_dir / "run_manifest.json").write_text(
                json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )

        final = current.resize(
            (args.target_width, args.target_height), Image.Resampling.LANCZOS
        )
        final, print_finish = adaptive_detail_guard(
            final,
            strength=args.print_detail_strength,
            radius=args.print_detail_radius,
            detail_threshold=args.print_detail_threshold,
            max_detail_delta=args.print_max_detail_delta,
        )
        dpi = args.target_height / (B5_HEIGHT_MM / 25.4)
        manifest["print_finish"] = print_finish
        manifest["b5_print"] = {
            "trim_mm": [182, 257],
            "pixel_size": [args.target_width, args.target_height],
            "effective_dpi_from_height": dpi,
            "color_space": "sRGB pixels; no printer-specific ICC conversion",
        }
        manifest["elapsed_seconds"] = time.perf_counter() - started
        summary = {
            "format_version": 1,
            "source_size": list(source.size),
            "target_size": [args.target_width, args.target_height],
            "tile_size": args.tile_size,
            "process_edge": args.process_edge,
            "stages": args.stages,
            "seed": args.seed,
            "protected_region_count": len(args.protect_ellipse),
            "effective_dpi": dpi,
        }
        output_name = f"{args.input.stem}_b5_4k.png"
        output_path = incomplete_dir / output_name
        final.save(
            output_path,
            format="PNG",
            pnginfo=pnginfo_for_output(source_info, summary),
            dpi=(dpi, dpi),
            optimize=True,
        )
        manifest["output"] = {
            "path": str(final_dir / output_name),
            "sha256": file_sha256(output_path),
            "size": [args.target_width, args.target_height],
        }
        remove_scoped_tree(work_dir, expected_parent=incomplete_dir)
        (incomplete_dir / "run_manifest.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        incomplete_dir.rename(final_dir)
        emit(f"OUTPUT_DIR={final_dir}")
        emit(f"IMAGE={final_dir / output_name}")
        emit(f"MANIFEST={final_dir / 'run_manifest.json'}")
        emit(f"DPI={dpi:.3f}")
        return 0
    except BaseException:
        if incomplete_dir.exists():
            remove_scoped_tree(incomplete_dir, expected_parent=args.output_root)
        raise


if __name__ == "__main__":
    raise SystemExit(main())
